name: 'Rancher Deploy Action'
description: 'Action to deploy docker image in rancher'
author: 'jammin.net'
branding:
  icon: 'check'
  color: 'gray-dark'
runs:
  using: 'docker'
  image: 'Dockerfile'
